import 'dart:async';
import 'package:socket_io_client/socket_io_client.dart' as IO;
import '../config/api_config.dart';
import '../models/booking_model.dart';
import '../models/user_model.dart';
import 'auth_service.dart';
import 'database_service.dart';

class BookingService {
  static final BookingService _instance = BookingService._internal();
  factory BookingService() => _instance;
  BookingService._internal();

  final _db = DatabaseService();
  final _auth = AuthService();
  IO.Socket? _socket;
  String? _cachedProviderId;
  String? _cachedProviderUserId;
  bool _refreshInProgress = false;
  DateTime? _lastRefreshAt;

  final _bookingsController = StreamController<List<Booking>>.broadcast();

  Stream<List<Booking>> get customerBookingsStream =>
      _bookingsController.stream;
  Stream<List<Booking>> get providerBookingsStream =>
      _bookingsController.stream;

  Future<String?> _resolveProviderId({bool forceRefresh = false}) async {
    final user = _auth.currentUser;
    if (user == null || user.role != UserRole.provider || user.id.isEmpty) {
      return null;
    }

    if (!forceRefresh &&
        _cachedProviderId != null &&
        _cachedProviderUserId == user.id) {
      return _cachedProviderId;
    }

    final provider = await _db.getProviderByUserId(user.id);
    if (provider != null && provider.id.isNotEmpty) {
      _cachedProviderId = provider.id;
      _cachedProviderUserId = user.id;
      return provider.id;
    }

    if (_cachedProviderUserId == user.id) {
      return _cachedProviderId;
    }

    return null;
  }

  Future<void> _joinCurrentUserRooms() async {
    if (_socket == null || _auth.currentUser == null) return;

    _socket!.emit('join_room', {'userId': _auth.currentUser!.id});
    if (_auth.currentUser!.role == UserRole.provider) {
      final providerId = await _resolveProviderId();
      if (providerId != null) {
        _socket!.emit('join_room', {'providerId': providerId});
      }
    }
  }

  // ─── Real-Time Initialization ──────────────────────────────────────────────

  void initializeSocket() {
    if (_socket != null) {
      if (_socket!.connected) {
        _joinCurrentUserRooms();
      }
      return;
    }

    _socket = IO.io(ApiConfig.socketUrl, <String, dynamic>{
      'transports': ['websocket'],
      'autoConnect': false,
    });

    _socket!.connect();

    _socket!.onConnect((_) async {
      print('SOCKET: Connected to server');
      await _joinCurrentUserRooms();
    });

    _socket!.on('new_booking', (data) {
      print('SOCKET: New booking received');
      _refreshBookings();
    });

    _socket!.on('booking_updated', (data) {
      print('SOCKET: Booking updated');
      _refreshBookings();
    });

    _socket!.onDisconnect((_) => print('SOCKET: Disconnected'));
  }

  Future<void> _refreshBookings() async {
    final now = DateTime.now();
    if (_refreshInProgress) return;
    if (_lastRefreshAt != null &&
        now.difference(_lastRefreshAt!) < const Duration(milliseconds: 400)) {
      return;
    }
    _refreshInProgress = true;
    _lastRefreshAt = now;
    try {
      if (_auth.currentUser?.role == UserRole.customer) {
        final b = await getCustomerBookings();
        _bookingsController.add(b);
      } else if (_auth.currentUser?.role == UserRole.provider) {
        final b = await getProviderBookings();
        _bookingsController.add(b);
      }
    } finally {
      _refreshInProgress = false;
    }
  }

  // ─── Create Booking ────────────────────────────────────────────────────────

  Future<({bool success, String? error, Booking? booking})> createBooking({
    required String providerId,
    required String serviceId,
    required String serviceName,
    required String providerName,
    required DateTime dateTime,
    required double price,
    required String address,
    String? specialInstructions,
  }) async {
    if (_auth.currentUser == null) {
      return (
        success: false,
        error: 'You must be logged in to create a booking.',
        booking: null,
      );
    }

    if (_auth.currentUser!.role != UserRole.customer) {
      return (
        success: false,
        error: 'Only customers can create bookings.',
        booking: null,
      );
    }

    print(
      'BOOKING_SERVICE: createBooking providerId=$providerId serviceId=$serviceId dateTime=${dateTime.toIso8601String()}',
    );

    final booking = Booking(
      id: '', // Generated by MongoDB
      customerId: _auth.currentUser!.id,
      providerId: providerId,
      serviceId: serviceId,
      customerName: _auth.currentUser!.name,
      providerName: providerName,
      serviceName: serviceName,
      dateTime: dateTime,
      status: BookingStatus.pending,
      price: price,
      address: address,
      specialInstructions: specialInstructions,
    );

    final result = await _db.insertBooking(booking);
    if (!result.success) {
      return (
        success: false,
        error: result.error ?? 'Booking failed',
        booking: null,
      );
    }

    await _refreshBookings();
    return (success: true, error: null, booking: result.booking ?? booking);
  }

  // ─── Queries ───────────────────────────────────────────────────────────────

  Future<List<Booking>> getCustomerBookings() =>
      _db.getBookingsByCustomer(_auth.currentUser!.id);

  Future<List<Booking>> getProviderBookings() async {
    final providerId = await _resolveProviderId();
    if (providerId == null) return [];
    return _db.getBookingsByProvider(providerId);
  }

  // ─── Status Updates ────────────────────────────────────────────────────────

  Future<bool> updateBookingStatus(
    String bookingId,
    BookingStatus newStatus,
  ) async {
    final ok = await _db.updateBookingStatus(bookingId, newStatus.toString().split('.').last);
    if (ok) _refreshBookings();
    return ok;
  }

  Future<bool> cancelBooking(String bookingId) =>
      updateBookingStatus(bookingId, BookingStatus.cancelled);

  Future<bool> acceptBooking(String bookingId) =>
      updateBookingStatus(bookingId, BookingStatus.accepted);

  Future<bool> rejectBooking(String bookingId) =>
      updateBookingStatus(bookingId, BookingStatus.rejected);

  Future<bool> completeBooking(String bookingId) =>
      updateBookingStatus(bookingId, BookingStatus.completed);

  Future<bool> submitFeedback(
    String bookingId, {
    required int rating,
    String? comment,
  }) async {
    final ok = await _db.submitBookingFeedback(
      bookingId: bookingId,
      rating: rating,
      comment: comment,
    );
    if (ok) _refreshBookings();
    return ok;
  }

  void dispose() {
    _socket?.dispose();
    _bookingsController.close();
  }
}
